pools:
  standard: 'singlecellmm10standard'

  highmem: 'singlecellmm10highmem'

  multicore: 'singlecellmm10multicore'

picard_wgs_params:
  # Minimum base quality to count a read
  min_bqual: 20

  # Minimum mapping quality to count a read
  min_mqual: 20

  # Count unpaired reads for wgs metrics
  count_unpaired: false

# HMMcopy parameters
hmmcopy_params:
  autoploidy:
    mu: 0,1,2,3,4,5,6,7,8,9,10,11

    m: 0,1,2,3,4,5,6,7,8,9,10,11

    kappa: 25,100,700,100,25,25,25,25,25,25,25,25

    e: 0.995

    g: 10

    s: 0.02

    nu: 2.1

    eta: 0.05,0.05,0.5,0.05,0.05,0.05,0.05,0.01,0.01,0.01,0.01,0.01

    lambda: 20

    strength: 1000

    # Optional mappability cutoff
    map_cutoff: 0.9

    # Number of states
    num_states: 12

    # Minimum mapping quality to count a read
    min_mqual: 20

    # Bin size
    bin_size: 500000

    # Binned GC content file
    gc_wig_file: /refdata/mm10_build38_mouse.gc.ws_500000.wig

    # Binned mappability file
    map_wig_file: /refdata/mm10_build38_mouse.map.rl_125_ws_500000.wig

    exclude_list: null

    smoothing_function: loess

    auto_ploidy: true

# Reference genome to align to in fasta format. Should be indexed by aligner and samtools
ref_genome: /refdata/mm10_build38_mouse.fasta

# Chromosomes for copy number analysis
chromosomes: ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16', '17', '18', '19', 'X', 'Y']

mutationseq: /usr/local/museq/

mutationseq_model: /usr/local/museq/models_anaconda/model_v4.1.2_anaconda_sk_0.13.1.npz

plot_mad_threshold: 0.2

plot_numreads_threshold: 100000

plot_quality_threshold: 0.5

gc_windows: null

one_split_job: True

memory:
  low: 2

  med: 6

  high: 15

max_cores: null

aligner: bwa-mem

adapter: 'CTGTCTCTTATACACATCTCCGAGCCCACGAGAC'

adapter2: 'CTGTCTCTTATACACATCTGACGCTGCCGACGA'
