# This file may be used to create an environment using:
# $ conda create --name <env> --file <this file>
# platform: linux-64
@EXPLICIT
https://repo.anaconda.com/pkgs/main/linux-64/_libgcc_mutex-0.1-main.conda
https://repo.anaconda.com/pkgs/main/linux-64/blas-1.0-mkl.conda
https://repo.anaconda.com/pkgs/main/linux-64/ca-certificates-2021.1.19-h06a4308_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/intel-openmp-2020.2-254.conda
https://repo.anaconda.com/pkgs/main/linux-64/ld_impl_linux-64-2.33.1-h53a641e_7.conda
https://repo.anaconda.com/pkgs/main/linux-64/libgfortran-ng-7.3.0-hdf63c60_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/libstdcxx-ng-9.1.0-hdf63c60_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/libgcc-ng-9.1.0-hdf63c60_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/mkl-2020.2-256.conda
https://repo.anaconda.com/pkgs/main/linux-64/bzip2-1.0.8-h7b6447c_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/expat-2.2.10-he6710b0_2.conda
https://repo.anaconda.com/pkgs/main/linux-64/icu-58.2-he6710b0_3.conda
https://repo.anaconda.com/pkgs/main/linux-64/jpeg-9b-h024ee3a_2.conda
https://repo.anaconda.com/pkgs/main/linux-64/libffi-3.3-he6710b0_2.conda
https://repo.anaconda.com/pkgs/main/linux-64/libgcc-7.2.0-h69d50b8_2.conda
https://repo.anaconda.com/pkgs/main/linux-64/libuuid-1.0.3-h1bed415_2.conda
https://repo.anaconda.com/pkgs/main/linux-64/libxcb-1.14-h7b6447c_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/lz4-c-1.9.3-h2531618_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/lzo-2.10-h7b6447c_2.conda
https://repo.anaconda.com/pkgs/main/linux-64/ncurses-6.2-he6710b0_0.tar.bz2
https://repo.anaconda.com/pkgs/main/linux-64/openssl-1.1.1j-h27cfd23_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/pcre-8.44-he6710b0_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/xz-5.2.5-h7b6447c_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/yaml-0.1.7-had09818_2.conda
https://repo.anaconda.com/pkgs/main/linux-64/zlib-1.2.11-h7b6447c_3.conda
https://conda.anaconda.org/dranew/linux-64/boost_lib-1.75.0-1.tar.bz2
https://repo.anaconda.com/pkgs/main/linux-64/glib-2.67.4-h36276a3_1.conda
https://repo.anaconda.com/pkgs/main/linux-64/hdf5-1.10.4-hb1b8bf9_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/libedit-3.1.20191231-h14c3975_1.conda
https://repo.anaconda.com/pkgs/main/linux-64/libpng-1.6.37-hbc83047_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/libssh2-1.9.0-h1ba5d50_1.conda
https://repo.anaconda.com/pkgs/main/linux-64/libxml2-2.9.10-hb55368b_3.conda
https://repo.anaconda.com/pkgs/main/linux-64/readline-7.0-h7b6447c_5.conda
https://repo.anaconda.com/pkgs/main/linux-64/tk-8.6.8-hbc83047_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/zstd-1.4.5-h9ceee32_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/blosc-1.21.0-h8c45485_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/dbus-1.13.18-hb2f20db_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/freetype-2.10.4-h5ab3b9f_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/gstreamer-1.14.0-h28cd5cc_2.conda
https://repo.anaconda.com/pkgs/main/linux-64/krb5-1.18.2-h173b8e3_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/libtiff-4.1.0-h2733197_1.conda
https://conda.anaconda.org/dranew/linux-64/shapeit-2.r904-0.tar.bz2
https://repo.anaconda.com/pkgs/main/linux-64/sqlite-3.31.1-h7b6447c_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/fontconfig-2.13.1-h6c09931_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/gst-plugins-base-1.14.0-h8213a91_2.conda
https://repo.anaconda.com/pkgs/main/linux-64/lcms2-2.11-h396b838_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/libcurl-7.71.1-h20c2e04_1.conda
https://repo.anaconda.com/pkgs/main/linux-64/python-3.7.6-h0371630_2.conda
https://repo.anaconda.com/pkgs/main/linux-64/asn1crypto-1.3.0-py37_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/certifi-2020.12.5-py37h06a4308_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/chardet-3.0.4-py37_1003.conda
https://repo.anaconda.com/pkgs/main/linux-64/curl-7.71.1-hbc83047_1.conda
https://repo.anaconda.com/pkgs/main/noarch/decorator-4.4.2-pyhd3eb1b0_0.tar.bz2
https://repo.anaconda.com/pkgs/main/noarch/dill-0.3.3-pyhd3eb1b0_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/future-0.18.2-py37_1.conda
https://repo.anaconda.com/pkgs/main/linux-64/idna-2.8-py37_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/kiwisolver-1.3.1-py37h2531618_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/markupsafe-1.1.1-py37h14c3975_1.conda
https://repo.anaconda.com/pkgs/main/noarch/mock-4.0.3-pyhd3eb1b0_0.conda
https://repo.anaconda.com/pkgs/main/noarch/nose-1.3.7-pyhd3eb1b0_1006.conda
https://repo.anaconda.com/pkgs/main/linux-64/olefile-0.46-py37_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/pycosat-0.6.3-py37h7b6447c_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/pycparser-2.19-py37_0.conda
https://repo.anaconda.com/pkgs/main/noarch/pyparsing-2.4.7-pyhd3eb1b0_0.tar.bz2
https://repo.anaconda.com/pkgs/main/linux-64/pysocks-1.7.1-py37_0.conda
https://repo.anaconda.com/pkgs/main/noarch/pytz-2021.1-pyhd3eb1b0_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/pyyaml-5.3.1-py37h7b6447c_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/qt-5.9.7-h5867ecd_1.conda
https://repo.anaconda.com/pkgs/main/linux-64/ruamel_yaml-0.15.87-py37h7b6447c_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/sip-4.19.8-py37hf484d3e_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/six-1.14.0-py37_0.conda
https://repo.anaconda.com/pkgs/main/noarch/threadpoolctl-2.1.0-pyh5ca1d4c_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/tornado-6.1-py37h27cfd23_0.conda
https://repo.anaconda.com/pkgs/main/noarch/tqdm-4.42.1-py_0.conda
https://repo.anaconda.com/pkgs/main/noarch/typing_extensions-3.7.4.3-pyha847dfd_0.tar.bz2
https://repo.anaconda.com/pkgs/main/linux-64/cffi-1.14.0-py37h2e261b9_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/conda-package-handling-1.6.0-py37h7b6447c_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/cycler-0.10.0-py37_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/mkl-service-2.3.0-py37he8ac12f_0.conda
https://repo.anaconda.com/pkgs/main/noarch/packaging-20.9-pyhd3eb1b0_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/pillow-8.1.0-py37he98fc37_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/pyqt-5.9.2-py37h05f1152_2.conda
https://repo.anaconda.com/pkgs/main/noarch/python-dateutil-2.8.1-pyhd3eb1b0_0.tar.bz2
https://conda.anaconda.org/dranew/linux-64/samtools-1.5-0.tar.bz2
https://repo.anaconda.com/pkgs/main/linux-64/setuptools-45.2.0-py37_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/cryptography-2.8-py37h1ba5d50_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/cython-0.29.22-py37h2531618_0.conda
https://repo.anaconda.com/pkgs/main/noarch/jinja2-2.11.3-pyhd3eb1b0_0.conda
https://repo.anaconda.com/pkgs/main/noarch/joblib-1.0.1-pyhd3eb1b0_0.conda
https://repo.anaconda.com/pkgs/main/noarch/networkx-2.5-py_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/numpy-base-1.19.2-py37hfa32c7d_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/wheel-0.34.2-py37_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/pip-20.0.2-py37_1.conda
https://repo.anaconda.com/pkgs/main/linux-64/pyopenssl-19.1.0-py37_0.conda
https://conda.anaconda.org/dranew/linux-64/pypeliner-0.5.18-py37_0.tar.bz2
https://repo.anaconda.com/pkgs/main/linux-64/urllib3-1.25.8-py37_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/requests-2.22.0-py37_1.conda
https://repo.anaconda.com/pkgs/main/linux-64/conda-4.9.2-py37h06a4308_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/bokeh-2.2.3-py37_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/matplotlib-3.3.4-py37h06a4308_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/matplotlib-base-3.3.4-py37h62a2d02_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/mkl_fft-1.2.1-py37h54f3939_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/mkl_random-1.1.1-py37h0573a6f_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/numpy-1.19.2-py37h54aff64_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/numexpr-2.7.2-py37hb2eb853_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/pandas-1.2.2-py37ha9443f7_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/scipy-1.6.1-py37h91f5cce_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/patsy-0.5.1-py37_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/pytables-3.6.1-py37h71ec239_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/scikit-learn-0.23.2-py37h0573a6f_0.conda
https://repo.anaconda.com/pkgs/main/noarch/seaborn-0.11.1-pyhd3eb1b0_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/statsmodels-0.12.2-py37h27cfd23_0.conda
https://conda.anaconda.org/dranew/linux-64/remixt-0.5.12-py37h39e3cac_0.tar.bz2
